/*
SQLyog Community v9.30 
MySQL - 5.6.25-log : Database - online-examination-sp
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`online-examination-sp` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `online-examination-sp`;

/*Table structure for table `EXAM` */

DROP TABLE IF EXISTS `EXAM`;

CREATE TABLE `EXAM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_DATETIME` datetime DEFAULT NULL,
  `EXAM_DATE` datetime DEFAULT NULL,
  `EXAM_NAME` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Data for the table `EXAM` */

/*Table structure for table `QUESTIONS` */

DROP TABLE IF EXISTS `QUESTIONS`;

CREATE TABLE `QUESTIONS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_DATETIME` datetime DEFAULT NULL,
  `CORRECT_ANS` varchar(225) DEFAULT NULL,
  `EXAM_NAME` varchar(225) DEFAULT NULL,
  `myAns` varchar(255) DEFAULT NULL,
  `OPTION1` varchar(225) DEFAULT NULL,
  `OPTION2` varchar(225) DEFAULT NULL,
  `OPTION3` varchar(225) DEFAULT NULL,
  `OPTION4` varchar(225) DEFAULT NULL,
  `QUESTION_NAME` varchar(225) DEFAULT NULL,
  `EXAM_ID` bigint(20) DEFAULT NULL,
  `pageNo` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Data for the table `QUESTIONS` */

/*Table structure for table `RESULT` */

DROP TABLE IF EXISTS `RESULT`;

CREATE TABLE `RESULT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_DATETIME` datetime DEFAULT NULL,
  `EXAM_DATE` date DEFAULT NULL,
  `EXAM_NAME` varchar(225) DEFAULT NULL,
  `RESULT` varchar(225) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `COUNT` varchar(225) DEFAULT NULL,
  `SIZE` varchar(225) DEFAULT NULL,
  `USER_NAME` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Data for the table `RESULT` */

/*Table structure for table `USER` */

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_DATETIME` datetime DEFAULT NULL,
  `ADDRESS` varchar(225) DEFAULT NULL,
  `confirmPassword` varchar(255) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `F_NAME` varchar(225) DEFAULT NULL,
  `GENDER` varchar(225) DEFAULT NULL,
  `L_NAME` varchar(225) DEFAULT NULL,
  `LOGIN` varchar(225) DEFAULT NULL,
  `MOBILE_NO` varchar(225) DEFAULT NULL,
  `PASSWORD` varchar(225) DEFAULT NULL,
  `ROLE_NAME` varchar(225) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  `QUALIFICATION` varchar(225) DEFAULT NULL,
  `SKILLS` varchar(225) DEFAULT NULL,
  `WORK_EXPERIENCE` varchar(225) DEFAULT NULL,
  `STATUS` varchar(225) DEFAULT NULL,
  `SUB_END_DATE` date DEFAULT NULL,
  `SUB_START_DATE` date DEFAULT NULL,
  `SUB_TYPE` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Data for the table `USER` */

insert  into `USER`(`ID`,`CREATED_BY`,`CREATED_DATETIME`,`MODIFIED_BY`,`MODIFIED_DATETIME`,`ADDRESS`,`confirmPassword`,`DOB`,`F_NAME`,`GENDER`,`L_NAME`,`LOGIN`,`MOBILE_NO`,`PASSWORD`,`ROLE_NAME`,`ROLE_ID`,`QUALIFICATION`,`SKILLS`,`WORK_EXPERIENCE`,`STATUS`,`SUB_END_DATE`,`SUB_START_DATE`,`SUB_TYPE`) values (1,NULL,NULL,NULL,NULL,'fgfdg',NULL,'1997-06-10','Admin','Male','Admin','Admin@gmail.com','9685454658','Admin@123',NULL,1,'dfsf','gdsg ','dfs',NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
